name: app_flutter_unidad_2_gds0553
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logotipo.jpg
  - assets/images/europa.jpg
  - assets/images/sevilla.jpg
  - assets/images/barcelona.png
  - assets/images/realmadrid.jpg
